name: hirafi
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.7.2
  ionicons: ^0.2.2
  carousel_slider: ^5.0.0
  shimmer: ^3.0.0
  font_awesome_flutter: ^10.8.0
  dotted_border: ^2.1.0
  lucide_icons: ^0.257.0
  flutter_otp_text_field: ^1.5.1+1
  flutter_datetime_picker_plus: ^2.2.0
  intl: ^0.19.0

dev_dependencies:
  flutter_launcher_icons: ^0.14.3
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_icons:
    android: true
    ios: true
    image_path: "assets/images/logos/app_icon.png"
    adaptive_icon_background: "#ffffff"  # Indigo background
    adaptive_icon_foreground: "assets/images/logos/app_icon_back.png"

flutter:
  generate: true

  uses-material-design: true

  assets:
    - assets/images/avatars/
    - assets/images/logos/
    - assets/icons/
    - assets/images/placeholders/
    - assets/images/previous_work/