import 'package:hirafi/utils/constants/urls.dart';

Map<String, List<String>> fieldsByCategory = {
  'Electrician': [
    'Wiring Installation',
    'Lighting Setup',
    'Circuit Breaker Repair',
    'Electrical Troubleshooting',
    'Ceiling Fan Installation',
    'Smart Home Systems',
  ],
  'Plumber': [
    'Leak Repair',
    'Water Heater Installation',
    'Bathroom Remodeling',
    'Drain Cleaning',
    'Pipe Fitting',
    'Toilet Installation',
  ],
  'Carpenter': [
    'Furniture Making',
    'Door and Window Installation',
    'Wood Flooring',
    'Cabinet Assembly',
    'Deck Construction',
    'Custom Shelving',
  ],
  'Painter': [
    'Interior Painting',
    'Exterior Painting',
    'Wallpaper Removal',
    'Furniture Painting',
    'Decorative Finishes',
    'Wall Repairs',
  ],
  'Tiler': [
    'Bathroom Tiling',
    'Kitchen Backsplash',
    'Floor Tiling',
    'Grout Cleaning',
    'Tile Repair',
    'Outdoor Patio Tiling',
  ],
  'Mason': [
    'Bricklaying',
    'Wall Construction',
    'Concrete Work',
    'Stone Paving',
    'Chimney Repair',
    'Fence Building',
  ],
  'Mechanic': [
    'Engine Repair',
    'Brake Replacement',
    'Oil Change',
    'Battery Replacement',
    'Transmission Service',
    'Vehicle Diagnostics',
  ],
  'Blacksmith': [
    'Gate Fabrication',
    'Window Grills',
    'Custom Metal Furniture',
    'Metal Door Making',
    'Repair Works',
    'Decorative Ironwork',
  ]
};

Map<String, List<String>> imagesByCategories = {
  'Electrician': [
    'assets/images/previous_work/elec1.jpeg',
    'assets/images/previous_work/elec2.jpeg',
    'assets/images/previous_work/elec3.jpeg',
    'assets/images/previous_work/elec4.jpg',
    'assets/images/previous_work/elec5.jpg',
    'assets/images/previous_work/elec6.jpg',
  ],
  'Plumber': [
    'assets/images/previous_work/plum1.jpg',
    'assets/images/previous_work/plum2.jpg',
    'assets/images/previous_work/plum3.jpg',
    'assets/images/previous_work/plum4.jpg',
    'assets/images/previous_work/plum5.jpeg',
  ],
  'Carpenter': [
    'assets/images/previous_work/carp1.jpg',
    'assets/images/previous_work/carp2.jpeg',
    'assets/images/previous_work/carp3.webp',
    'assets/images/previous_work/carp4.jpeg',
    'assets/images/previous_work/carp5.png',
  ],
  'Painter': [
    'assets/images/previous_work/paint1.jpeg',
    'assets/images/previous_work/paint2.jpeg',
    'assets/images/previous_work/paint3.jpg',
    'assets/images/previous_work/paint4.jpeg',
    'assets/images/previous_work/paint5.jpeg',
  ],
  'Mason': [
    'assets/images/previous_work/mason1.jpg',
    'assets/images/previous_work/mason2.jpg',
    'assets/images/previous_work/mason3.jpg',
    'assets/images/previous_work/mason4.jpg',
    'assets/images/previous_work/mason5.webp',
  ],
  'Mechanic': [
    'assets/images/previous_work/mec1.jpeg',
    'assets/images/previous_work/mec2.jpeg',
    'assets/images/previous_work/mec3.jpeg',
    'assets/images/previous_work/mec4.jpg',
    'assets/images/previous_work/mec5.jpeg',
  ],
};

// Mock data for artisanDummyData (replace with actual data from your backend)
final List<Map<String, dynamic>> artisanDummyData = [
  {
    'id': 1,
    'fullName': 'Ali Mansouri',
    'location': 'Algiers',
    'email': 'ali.mansouri@example.com',
    'phoneNumber': '+213661234567',
    'password': 'password123',
    'avatar': '$AVATARS_URL/electrician_avatar.jpg',
    'category': 'Electrician',
    'stars': 4.8,
  },
  {
    'id': 2,
    'fullName': 'Sami Bouzid',
    'location': 'Oran',
    'email': 'sami.bouzid@example.com',
    'phoneNumber': '+213662345678',
    'password': 'password123',
    'avatar': '$AVATARS_URL/plumber_avatar.jpeg',
    'category': 'Plumber',
    'stars': 4.7,
  },
  {
    'id': 3,
    'fullName': 'Islem Bensalem',
    'location': 'Constantine',
    'email': 'meriem.bensalem@example.com',
    'phoneNumber': '+213663456789',
    'password': 'password123',
    'avatar': '$AVATARS_URL/car_avatar.jpeg',
    'category': 'Carpenter',
    'stars': 4.5,
  },
  {
    'id': 4,
    'fullName': 'Khaled Haroun',
    'location': 'Blida',
    'email': 'khaled.haroun@example.com',
    'phoneNumber': '+213664567890',
    'password': 'password123',
    'avatar': '$AVATARS_URL/painter_avatar.jpg',
    'category': 'Painter',
    'stars': 4.2,
  },
];

final Map<String, List<String>> artisanServices = {
  "Electricity": [
    "Repair sudden faults and power outages",
    "Inspect and update old wiring",
    "Maintain breakers and electrical switches",
    "Maintain indoor and outdoor lighting",
    "Repair distribution and control panels",
    "Maintain solar energy systems and batteries",
    "Repair smart home systems and remote controls",
  ],
  "Plumbing": [
    "Detect and repair water leaks",
    "Repair pipes, valves, and tanks",
    "Unclog blocked drains and sewers",
    "Maintain water heaters and pumps",
    "Replace damaged mixers and faucets",
    "Fix water pressure and heating issues",
  ],
  "Carpentry": [
    "Repair wooden doors and windows",
    "Maintain cabinets and kitchens",
    "Modify and restore old furniture",
    "Fix hinges, handles, and drawers",
    "Treat moisture or wood decay",
    "Maintain bedrooms, tables, and chairs",
  ],
  "Ironwork": [
    "Repair iron doors and windows",
    "Weld cracks in metal structures",
    "Reinforce and maintain stairs",
    "Fix garages and iron fences",
    "Reinstall loose parts",
  ],
  "Aluminum and Glass": [
    "Repair aluminum windows and doors",
    "Adjust broken or unaligned glass frames",
    "Replace sliding door wheels",
    "Install new glass and fix cracked glass",
    "Maintain store glass facades",
  ],
  "Painting and Decoration": [
    "Repair and peel damaged paint",
    "Repaint walls and ceilings",
    "Treat moisture and cracks",
    "Repair decorative and artistic paintwork",
    "Maintain or remove wallpaper",
  ],
  "Gypsum and Finishing": [
    "Repair cracked or fallen gypsum",
    "Maintain gypsum wall decorations",
    "Fix hidden lighting problems",
    "Restore partitions and suspended ceilings",
  ],
  "Air Conditioning and Refrigeration": [
    "Inspect and maintain split and central AC units",
    "Recharge Freon and clean filters",
    "Fix cooling or leakage problems",
    "Adjust control units and timers",
  ],
  "Construction and Contracting": [
    "Repair wall and ceiling cracks",
    "Treat moisture and water leaks",
    "Restore damaged facades and blocks",
    "Rebuild or modify parts of the house",
    "Fix floor or foundation settlement",
  ],
  "Ceramics and Tiling": [
    "Replace cracked or loose tiles",
    "Repair tile corners and joints",
    "Treat moisture under tiles",
    "Restore granite or marble works",
  ],
  "Gardening and Landscaping": [
    "Maintain automatic irrigation systems",
    "Rehabilitate damaged gardens",
    "Prune trees and plants",
    "Treat agricultural pests",
    "Restore garden flooring (tiles or artificial grass)",
  ],
  "Cleaning": [
    "Clean after renovation works",
    "Sanitize homes or offices",
    "Clean furniture (sofa, carpet, curtains)",
    "Clean water tanks and rooftops",
    "Remove tough stains or odors",
  ],
  "Electronics and Technology": [
    "Maintain surveillance cameras",
    "Repair satellite receivers",
    "Check internet networks and devices",
    "Maintain screens and televisions",
  ],
  "Curtains and Shades": [
    "Repair electric curtain faults",
    "Adjust or reinstall fixed curtains",
    "Maintain parking or garden shades",
    "Replace damaged parts or fabric",
  ],
  "Home Appliances Repair": [
    "Maintain washing machines and refrigerators",
    "Repair ovens and microwaves",
    "Replace spare parts for home appliances",
    "Fix internal electrical faults",
  ],
  "Moving and Assembly": [
    "Disassemble and assemble furniture, fixing damages",
    "Adjust furniture to fit new spaces",
    "Secure unstable furniture pieces",
    "Provide safe lifting and moving services",
  ],
  "Elevator Maintenance": [
    "Repair electrical or mechanical faults",
    "Check safety and emergency stops",
    "Update control systems",
    "Maintain doors and motors",
  ],
  "Interior and Exterior Design": [
    "Modify or repair interior finishes",
    "Update decoration by taste or need",
    "Fix lighting and gypsum faults",
    "Optimize existing space usage",
  ],
  "Thermal and Waterproofing": [
    "Repair leaks from roofs and tanks",
    "Treat damp walls",
    "Maintain old insulation materials",
    "Inspect insulation efficiency and re-cover",
  ],
  "Security and Control Services": [
    "Maintain alarm and fingerprint systems",
    "Repair smart locks",
    "Update surveillance systems",
    "Reprogram entrance gates",
  ],
  "Water Tanks": [
    "Clean and sanitize water tanks",
    "Fix faults or leaks",
    "Check water floats and valves",
    "Maintain tank covers",
  ],
  "Outdoor and Indoor Games Maintenance": [
    "Repair slides and playgrounds",
    "Secure loose playground equipment",
    "Replace plastic or metal parts",
    "Maintain home electronic games",
  ],
  "Alternative Energy Systems": [
    "Clean and maintain solar panels",
    "Check batteries and inverters",
    "Maintain alternative energy wiring",
  ],
};
