import 'package:hirafi/utils/constants/urls.dart';

Map<String, List<String>> fieldsByCategory = {
  'Electrician': [
    'Wiring Installation',
    'Lighting Setup',
    'Circuit Breaker Repair',
    'Electrical Troubleshooting',
    'Ceiling Fan Installation',
    'Smart Home Systems',
  ],
  'Plumber': [
    'Leak Repair',
    'Water Heater Installation',
    'Bathroom Remodeling',
    'Drain Cleaning',
    'Pipe Fitting',
    'Toilet Installation',
  ],
  'Carpenter': [
    'Furniture Making',
    'Door and Window Installation',
    'Wood Flooring',
    'Cabinet Assembly',
    'Deck Construction',
    'Custom Shelving',
  ],
  'Painter': [
    'Interior Painting',
    'Exterior Painting',
    'Wallpaper Removal',
    'Furniture Painting',
    'Decorative Finishes',
    'Wall Repairs',
  ],
  'Tiler': [
    'Bathroom Tiling',
    'Kitchen Backsplash',
    'Floor Tiling',
    'Grout Cleaning',
    'Tile Repair',
    'Outdoor Patio Tiling',
  ],
  'Mason': [
    'Bricklaying',
    'Wall Construction',
    'Concrete Work',
    'Stone Paving',
    'Chimney Repair',
    'Fence Building',
  ],
  'Mechanic': [
    'Engine Repair',
    'Brake Replacement',
    'Oil Change',
    'Battery Replacement',
    'Transmission Service',
    'Vehicle Diagnostics',
  ],
  'Blacksmith': [
    'Gate Fabrication',
    'Window Grills',
    'Custom Metal Furniture',
    'Metal Door Making',
    'Repair Works',
    'Decorative Ironwork',
  ]
};

Map<String, List<String>> imagesByCategories = {
  'Electrician': [
    'assets/images/previous_work/elec1.jpeg',
    'assets/images/previous_work/elec2.jpeg',
    'assets/images/previous_work/elec3.jpeg',
    'assets/images/previous_work/elec4.jpg',
    'assets/images/previous_work/elec5.jpg',
    'assets/images/previous_work/elec6.jpg',
  ],
  'Plumber': [
    'assets/images/previous_work/plum1.jpg',
    'assets/images/previous_work/plum2.jpg',
    'assets/images/previous_work/plum3.jpg',
    'assets/images/previous_work/plum4.jpg',
    'assets/images/previous_work/plum5.jpeg',
  ],
  'Carpenter': [
    'assets/images/previous_work/carp1.jpg',
    'assets/images/previous_work/carp2.jpeg',
    'assets/images/previous_work/carp3.webp',
    'assets/images/previous_work/carp4.jpeg',
    'assets/images/previous_work/carp5.png',
  ],
  'Painter': [
    'assets/images/previous_work/paint1.jpeg',
    'assets/images/previous_work/paint2.jpeg',
    'assets/images/previous_work/paint3.jpg',
    'assets/images/previous_work/paint4.jpeg',
    'assets/images/previous_work/paint5.jpeg',
  ],
  'Mason': [
    'assets/images/previous_work/mason1.jpg',
    'assets/images/previous_work/mason2.jpg',
    'assets/images/previous_work/mason3.jpg',
    'assets/images/previous_work/mason4.jpg',
    'assets/images/previous_work/mason5.webp',
  ],
  'Mechanic': [
    'assets/images/previous_work/mec1.jpeg',
    'assets/images/previous_work/mec2.jpeg',
    'assets/images/previous_work/mec3.jpeg',
    'assets/images/previous_work/mec4.jpg',
    'assets/images/previous_work/mec5.jpeg',
  ],
};

// Mock data for artisanDummyData (replace with actual data from your backend)
final List<Map<String, dynamic>> artisanDummyData = [
  {
    'id': 1,
    'fullName': 'Ali Mansouri',
    'location': 'Algiers',
    'email': 'ali.mansouri@example.com',
    'phoneNumber': '+213661234567',
    'password': 'password123',
    'avatar': '$AVATARS_URL/electrician_avatar.jpg',
    'category': 'Electrician',
    'stars': 4.8,
  },
  {
    'id': 2,
    'fullName': 'Sami Bouzid',
    'location': 'Oran',
    'email': 'sami.bouzid@example.com',
    'phoneNumber': '+213662345678',
    'password': 'password123',
    'avatar': '$AVATARS_URL/plumber_avatar.jpeg',
    'category': 'Plumber',
    'stars': 4.7,
  },
  {
    'id': 3,
    'fullName': 'Islem Bensalem',
    'location': 'Constantine',
    'email': 'meriem.bensalem@example.com',
    'phoneNumber': '+213663456789',
    'password': 'password123',
    'avatar': '$AVATARS_URL/car_avatar.jpeg',
    'category': 'Carpenter',
    'stars': 4.5,
  },
  {
    'id': 4,
    'fullName': 'Khaled Haroun',
    'location': 'Blida',
    'email': 'khaled.haroun@example.com',
    'phoneNumber': '+213664567890',
    'password': 'password123',
    'avatar': '$AVATARS_URL/painter_avatar.jpg',
    'category': 'Painter',
    'stars': 4.2,
  },
];
