import 'package:hirafi/utils/constants/urls.dart';

Map<String, List<String>> fieldsByCategory = {
  'Electrician': [
    'Wiring Installation',
    'Lighting Setup',
    'Circuit Breaker Repair',
    'Electrical Troubleshooting',
    'Ceiling Fan Installation',
    'Smart Home Systems',
  ],
  'Plumber': [
    'Leak Repair',
    'Water Heater Installation',
    'Bathroom Remodeling',
    'Drain Cleaning',
    'Pipe Fitting',
    'Toilet Installation',
  ],
  'Carpenter': [
    'Furniture Making',
    'Door and Window Installation',
    'Wood Flooring',
    'Cabinet Assembly',
    'Deck Construction',
    'Custom Shelving',
  ],
  'Painter': [
    'Interior Painting',
    'Exterior Painting',
    'Wallpaper Removal',
    'Furniture Painting',
    'Decorative Finishes',
    'Wall Repairs',
  ],
  'Tiler': [
    'Bathroom Tiling',
    'Kitchen Backsplash',
    'Floor Tiling',
    'Grout Cleaning',
    'Tile Repair',
    'Outdoor Patio Tiling',
  ],
  'Mason': [
    'Bricklaying',
    'Wall Construction',
    'Concrete Work',
    'Stone Paving',
    'Chimney Repair',
    'Fence Building',
  ],
  'Mechanic': [
    'Engine Repair',
    'Brake Replacement',
    'Oil Change',
    'Battery Replacement',
    'Transmission Service',
    'Vehicle Diagnostics',
  ],
  'Blacksmith': [
    'Gate Fabrication',
    'Window Grills',
    'Custom Metal Furniture',
    'Metal Door Making',
    'Repair Works',
    'Decorative Ironwork',
  ]
};

Map<String, List<String>> imagesByCategories = {
  'Electrician': [
    'assets/images/previous_work/elec1.jpeg',
    'assets/images/previous_work/elec2.jpeg',
    'assets/images/previous_work/elec3.jpeg',
    'assets/images/previous_work/elec4.jpg',
    'assets/images/previous_work/elec5.jpg',
    'assets/images/previous_work/elec6.jpg',
  ],
  'Plumber': [
    'assets/images/previous_work/plum1.jpg',
    'assets/images/previous_work/plum2.jpg',
    'assets/images/previous_work/plum3.jpg',
    'assets/images/previous_work/plum4.jpg',
    'assets/images/previous_work/plum5.jpeg',
  ],
  'Carpenter': [
    'assets/images/previous_work/carp1.jpg',
    'assets/images/previous_work/carp2.jpeg',
    'assets/images/previous_work/carp3.webp',
    'assets/images/previous_work/carp4.jpeg',
    'assets/images/previous_work/carp5.png',
  ],
  'Painter': [
    'assets/images/previous_work/paint1.jpeg',
    'assets/images/previous_work/paint2.jpeg',
    'assets/images/previous_work/paint3.jpg',
    'assets/images/previous_work/paint4.jpeg',
    'assets/images/previous_work/paint5.jpeg',
  ],
  'Mason': [
    'assets/images/previous_work/mason1.jpg',
    'assets/images/previous_work/mason2.jpg',
    'assets/images/previous_work/mason3.jpg',
    'assets/images/previous_work/mason4.jpg',
    'assets/images/previous_work/mason5.webp',
  ],
  'Mechanic': [
    'assets/images/previous_work/mec1.jpeg',
    'assets/images/previous_work/mec2.jpeg',
    'assets/images/previous_work/mec3.jpeg',
    'assets/images/previous_work/mec4.jpg',
    'assets/images/previous_work/mec5.jpeg',
  ],
};

// Mock data for artisanDummyData (replace with actual data from your backend)
final List<Map<String, dynamic>> artisanDummyData = [
  {
    'id': 1,
    'fullName': 'Ali Mansouri',
    'location': 'Algiers',
    'email': 'ali.mansouri@example.com',
    'phoneNumber': '+213661234567',
    'password': 'password123',
    'avatar': '$AVATARS_URL/electrician_avatar.jpg',
    'category': 'Electrician',
    'stars': 4.8,
  },
  {
    'id': 2,
    'fullName': 'Sami Bouzid',
    'location': 'Oran',
    'email': 'sami.bouzid@example.com',
    'phoneNumber': '+213662345678',
    'password': 'password123',
    'avatar': '$AVATARS_URL/plumber_avatar.jpeg',
    'category': 'Plumber',
    'stars': 4.7,
  },
  {
    'id': 3,
    'fullName': 'Islem Bensalem',
    'location': 'Constantine',
    'email': 'meriem.bensalem@example.com',
    'phoneNumber': '+213663456789',
    'password': 'password123',
    'avatar': '$AVATARS_URL/car_avatar.jpeg',
    'category': 'Carpenter',
    'stars': 4.5,
  },
  {
    'id': 4,
    'fullName': 'Khaled Haroun',
    'location': 'Blida',
    'email': 'khaled.haroun@example.com',
    'phoneNumber': '+213664567890',
    'password': 'password123',
    'avatar': '$AVATARS_URL/painter_avatar.jpg',
    'category': 'Painter',
    'stars': 4.2,
  },
];

final Map<String, List<String>> artisanServices = {
  "الكهرباء": [
    "إصلاح الأعطال المفاجئة وانقطاع التيار",
    "فحص وتحديث الأسلاك القديمة",
    "صيانة القواطع والمفاتيح الكهربائية",
    "صيانة الإضاءة الداخلية والخارجية",
    "إصلاح لوحات التوزيع والتحكم",
    "صيانة أنظمة الطاقة الشمسية والبطاريات",
    "إصلاح أنظمة المنزل الذكي وأجهزة التحكم عن بعد",
  ],
  "السباكة": [
    "كشف وإصلاح تسربات المياه",
    "إصلاح الأنابيب والصمامات والخزانات",
    "فتح المجاري والصرف الصحي المسدود",
    "صيانة مدافئ المياه والمضخات",
    "استبدال الخلاطات والصنابير التالفة",
    "إصلاح مشاكل ضغط المياه والتدفئة",
  ],
  "النجارة": [
    "إصلاح الأبواب والنوافذ الخشبية",
    "صيانة الخزائن والمطابخ",
    "تعديل وترميم الأثاث القديم",
    "إصلاح المفصلات والمقابض والأدراج",
    "معالجة الرطوبة أو تسوس الخشب",
    "صيانة غرف النوم والطاولات والكراسي",
  ],
  "الدهان والديكور": [
    "إصلاح وتقشير الدهان التالف",
    "إعادة طلاء الجدران والأسقف",
    "معالجة الرطوبة والشقوق",
    "إصلاح الدهانات الزخرفية والفنية",
    "صيانة أو إزالة ورق الحائط",
  ],
  "الأعمال الحديدية": [
    "إصلاح الأبواب والنوافذ الحديدية",
    "لحام الشقوق في الهياكل المعدنية",
    "تعزيز وصيانة السلالم",
    "إصلاح الجراجات والأسوار الحديدية",
    "إعادة تركيب الأجزاء المفكوكة",
  ],
  "الألمنيوم والزجاج": [
    "إصلاح نوافذ وأبواب الألمنيوم",
    "تعديل إطارات الزجاج المكسورة أو غير المحاذية",
    "استبدال عجلات الأبواب الزلقة",
    "تركيب زجاج جديد وإصلاح الزجاج المتصدع",
    "صيانة واجهات الزجاج للمتاجر",
  ],
  "الجبس والتشطيب": [
    "إصلاح الجبس المتشقق أو الساقط",
    "صيانة زخارف جدران الجبس",
    "إصلاح مشاكل الإضاءة المخفية",
    "ترميم الحواجز والأسقف المعلقة",
  ],
  "التكييف والتبريد": [
    "فحص وصيانة وحدات التكييف المقسمة والمركزية",
    "إعادة شحن الفريون وتنظيف الفلاتر",
    "إصلاح مشاكل التبريد أو التسرب",
    "تعديل وحدات التحكم والمؤقتات",
  ],
  "البناء والمقاولات": [
    "إصلاح شقوق الجدران والأسقف",
    "معالجة الرطوبة وتسربات المياه",
    "ترميم الواجهات والكتل التالفة",
    "إعادة بناء أو تعديل أجزاء من المنزل",
    "إصلاح تسوية الأرضيات أو الأساسات",
  ],
  "السيراميك والبلاط": [
    "استبدال البلاط المتشقق أو المفكوك",
    "إصلاح زوايا وفواصل البلاط",
    "معالجة الرطوبة تحت البلاط",
    "ترميم أعمال الجرانيت أو الرخام",
  ],
  "البستنة والتنسيق": [
    "صيانة أنظمة الري الآلية",
    "تأهيل الحدائق التالفة",
    "تقليم الأشجار والنباتات",
    "معالجة الآفات الزراعية",
    "ترميم أرضيات الحدائق (بلاط أو عشب صناعي)",
  ],
  "التنظيف": [
    "التنظيف بعد أعمال التجديد",
    "تعقيم المنازل أو المكاتب",
    "تنظيف الأثاث (أريكة، سجاد، ستائر)",
    "تنظيف خزانات المياه والأسطح",
    "إزالة البقع أو الروائح الصعبة",
  ],
  "الإلكترونيات والتكنولوجيا": [
    "صيانة كاميرات المراقبة",
    "إصلاح أجهزة استقبال الأقمار الصناعية",
    "فحص شبكات الإنترنت والأجهزة",
    "صيانة الشاشات والتلفزيونات",
  ],
  "الستائر والمظلات": [
    "إصلاح أعطال الستائر الكهربائية",
    "تعديل أو إعادة تركيب الستائر الثابتة",
    "صيانة مظلات المواقف أو الحدائق",
    "استبدال الأجزاء أو الأقمشة التالفة",
  ],
  "إصلاح الأجهزة المنزلية": [
    "صيانة الغسالات والثلاجات",
    "إصلاح الأفران والميكروويف",
    "استبدال قطع غيار الأجهزة المنزلية",
    "إصلاح الأعطال الكهربائية الداخلية",
  ],
  "النقل والتجميع": [
    "تفكيك وتجميع الأثاث مع إصلاح الأضرار",
    "تعديل الأثاث ليتناسب مع المساحات الجديدة",
    "تثبيت قطع الأثاث غير المستقرة",
    "توفير خدمات رفع ونقل آمنة",
  ],
  "صيانة المصاعد": [
    "إصلاح الأعطال الكهربائية أو الميكانيكية",
    "فحص الأمان والتوقف الطارئ",
    "تحديث أنظمة التحكم",
    "صيانة الأبواب والمحركات",
  ],
  "التصميم الداخلي والخارجي": [
    "تعديل أو إصلاح التشطيبات الداخلية",
    "تحديث الديكور حسب الذوق أو الحاجة",
    "إصلاح أعطال الإضاءة والجبس",
    "تحسين استخدام المساحة الحالية",
  ],
  "العزل الحراري والمائي": [
    "إصلاح التسربات من الأسطح والخزانات",
    "معالجة الجدران الرطبة",
    "صيانة مواد العزل القديمة",
    "فحص كفاءة العزل وإعادة التغطية",
  ],
  "خدمات الأمن والتحكم": [
    "صيانة أنظمة الإنذار وبصمات الأصابع",
    "إصلاح الأقفال الذكية",
    "تحديث أنظمة المراقبة",
    "إعادة برمجة بوابات الدخول",
  ],
  "خزانات المياه": [
    "تنظيف وتعقيم خزانات المياه",
    "إصلاح الأعطال أو التسربات",
    "فحص عوامات وصمامات المياه",
    "صيانة أغطية الخزانات",
  ],
  "صيانة الألعاب الخارجية والداخلية": [
    "إصلاح الزحاليق وملاعب الأطفال",
    "تثبيت معدات الملاعب المفكوكة",
    "استبدال الأجزاء البلاستيكية أو المعدنية",
    "صيانة الألعاب الإلكترونية المنزلية",
  ],
  "أنظمة الطاقة البديلة": [
    "تنظيف وصيانة الألواح الشمسية",
    "فحص البطاريات والمحولات",
    "صيانة أسلاك الطاقة البديلة",
  ],
};
